services:
  mongo:
    image: docker.io/library/mongo:4.4
    container_name: mongo
    restart: always
    volumes:
      - /media/benyedde/rootfs/bestflats_data/mongo:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    container_name: backend
    restart: always
    environment:
      - SMTP_URL=smtp://mailhog:1025
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - mailhog

  mailhog:
    image: docker.io/mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mcp-client:
    build:
      context: ./mcp-client
      dockerfile: Containerfile
    container_name: mcp-client
    environment:
      - BACKEND_URL=http://backend:4000
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  mongo_data:
