FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY src ./src
COPY uploads ./uploads
COPY tests ./tests
COPY jest.config.cjs .

EXPOSE 4000

CMD ["node", "src/index.js"]
