FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

# copy only the app files we need for build
COPY pages ./pages
COPY styles ./styles

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
